---
title: "Assignment 1: Introduction"
author: "Pierre Mishra"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on Tuesday, January 14th at 1:00 pm.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took 'Applied Data Analysis in R' with Betsy Albright in the Fall 2019. In my own time, I do an online data science course from Dataquest.io in Python. At the end of each lesson, Dataquest.io has a guided project for which I use Jupyter notebook. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel a little confident in data cleaning and visualization but not much.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am not good at selecting models, I believe. So I am looking forward to learning more about applying appropriate models and visualizations.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/peacefulpierre/Environmental_Data_Analytics_2020 


